from enum import StrEnum


class ErrorCode(StrEnum):
    # 400x Client Errors
    INVALID_QUERY = "UNISAGE_4001_INVALID_QUERY"
    UNAUTHORIZED = "UNISAGE_4002_UNAUTHORIZED"

    # 500x Server & LLM Errors
    LLM_TIMEOUT = "UNISAGE_5001_LLM_TIMEOUT"
    LLM_PROVIDER_ERROR = "UNISAGE_5002_LLM_PROVIDER_ERROR"
    DATABASE_ERROR = "UNISAGE_5003_DATABASE_ERROR"
    INTERNAL_ERROR = "UNISAGE_5000_INTERNAL_ERROR"
