from enum import StrEnum


class ErrorCode(StrEnum):
    # 400x Client Errors
    INVALID_QUERY = "UNISAGE_4001_INVALID_QUERY"
    UNAUTHORIZED = "UNISAGE_4002_UNAUTHORIZED"
    MISSING_TRUSTED_CONTEXT = "UNISAGE_4003_MISSING_TRUSTED_CONTEXT"
    UNSUPPORTED_FILE_TYPE = "UNISAGE_4004_UNSUPPORTED_FILE_TYPE"
    STRATEGY_FILE_TYPE_MISMATCH = "UNISAGE_4005_STRATEGY_FILE_TYPE_MISMATCH"
    INVALID_TRUSTED_CONTEXT = "UNISAGE_4006_INVALID_TRUSTED_CONTEXT"
    FORBIDDEN_DOCUMENT_PERMISSION = "UNISAGE_4007_FORBIDDEN_DOCUMENT_PERMISSION"
    FORBIDDEN_DEPARTMENT_ACCESS = "UNISAGE_4008_FORBIDDEN_DEPARTMENT_ACCESS"

    # 404x Not Found Errors
    OBJECT_NOT_FOUND = "UNISAGE_4041_OBJECT_NOT_FOUND"

    # 500x Server & LLM Errors
    LLM_TIMEOUT = "UNISAGE_5001_LLM_TIMEOUT"
    LLM_PROVIDER_ERROR = "UNISAGE_5002_LLM_PROVIDER_ERROR"
    DATABASE_ERROR = "UNISAGE_5003_DATABASE_ERROR"
    INTERNAL_ERROR = "UNISAGE_5000_INTERNAL_ERROR"
